from datetime import timedelta
from src.config import settings
from enum import StrEnum

# BEZPIECZEŃSTWO - Tokeny i cookies

ACCESS_TOKEN_COOKIE = "access_token"
REFRESH_TOKEN_COOKIE = "refresh_token"
CSRF_TOKEN_COOKIE = "XSRF-TOKEN"

ACCESS_TOKEN_EXPIRE_MINUTES = settings.ACCESS_TOKEN_EXPIRE_MINUTES
REFRESH_TOKEN_EXPIRE_DAYS = settings.REFRESH_TOKEN_EXPIRE_DAYS

ACCESS_TOKEN_MAX_AGE = ACCESS_TOKEN_EXPIRE_MINUTES * 60
REFRESH_TOKEN_MAX_AGE = REFRESH_TOKEN_EXPIRE_DAYS * 24 * 60 * 60
CSRF_TOKEN_MAX_AGE = REFRESH_TOKEN_MAX_AGE 

ACCESS_TOKEN_EXPIRE_DELTA = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
REFRESH_TOKEN_EXPIRE_DELTA = timedelta(days=REFRESH_TOKEN_EXPIRE_DAYS)

CSRF_HEADER_NAME = "X-XSRF-TOKEN"
WWW_AUTHENTICATE_HEADER = "Bearer"

# ROLE UŻYTKOWNIKÓW

ROLE_READER = "reader"
ROLE_ADMIN = "admin"

# BEZPIECZEŃSTWO - Hasła

BCRYPT_ROUNDS = 12
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_BYTES = 72 

# WYPOŻYCZENIA - Limity i czasy trwania

MAX_ACTIVE_LOANS = 5

LOAN_DURATION_DAYS = 14

# PAGINACJA - Domyślne wartości

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# PLACEHOLDERS - Tymczasowe wartości dla encji oczekujących na wzbogacenie

PLACEHOLDER_TITLE = "Wczytywanie..."

# STATUSY - Dostępne wartości dla encji


class LoanStatus(StrEnum):
    ACTIVE = "active"
    RETURNED = "returned"
    OVERDUE = "overdue"


class LoanRequestStatus(StrEnum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    CANCELLED = "cancelled"


class MessageType(StrEnum):
    TEXT = "text"
    SYSTEM = "system"

# IMPORTY - Walidacja ISBN

ISBN_MIN_LENGTH = 10
ISBN_MAX_LENGTH = 17

# WIADOMOŚCI - Ograniczenia

MESSAGE_MAX_LENGTH = 2000
MESSAGE_MIN_LENGTH = 1
LOAN_REQUEST_MESSAGE_MAX_LENGTH = 1000

# HTTP STATUS KODY

HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_204_NO_CONTENT = 204
HTTP_400_BAD_REQUEST = 400
HTTP_401_UNAUTHORIZED = 401
HTTP_403_FORBIDDEN = 403
HTTP_404_NOT_FOUND = 404
HTTP_409_CONFLICT = 409
HTTP_422_UNPROCESSABLE_ENTITY = 422
HTTP_500_INTERNAL_SERVER_ERROR = 500

# KOMUNIKATY BŁĘDÓW

ERROR_CSRF_TOKEN_INVALID = "Invalid CSRF token"
ERROR_CSRF_TOKEN_MISSING = "CSRF token missing"
ERROR_INACTIVE_USER = "User account is inactive"
ERROR_INVALID_TOKEN = "Invalid authentication token"
ERROR_MISSING_TOKEN = "Authentication token missing"
ERROR_INVALID_CREDENTIALS = "Invalid email or password"
ERROR_TOKEN_REVOKED = "Token has been revoked"

# KOMUNIKATY SUKCESU

MSG_LOGIN_SUCCESS = "Login successful"
MSG_LOGOUT_SUCCESS = "Logout successful"
MSG_REGISTER_SUCCESS = "User registered successfully"
MSG_TOKEN_REFRESHED = "Token refreshed successfully"
